// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang.Data;

#nullable disable

namespace WebBanHang.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260530073152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanHang.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desktop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Smartphones"
                        });
                });

            modelBuilder.Entity("WebBanHang.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Apple Silicon, 16GB RAM, 512GB SSD",
                            ImageUrl = "/images/MacBook Pro M3.jpg",
                            Name = "MacBook Pro M3",
                            Price = 29000000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Intel i7, 4K Display, Great for creators",
                            ImageUrl = "/images/Dell XPS 15.jpg",
                            ImageUrls = "[\"/images/Dell XPS 15 2.jpg\",\"/images/Dell XPS 15 3.jpg\"]",
                            Name = "Dell XPS 15",
                            Price = 15000000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "High-end gaming laptop with RTX 4070",
                            ImageUrl = "/images/ASUS ROG Zephyrus.jpg",
                            Name = "ASUS ROG Zephyrus",
                            Price = 18000000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "All-in-one desktop with M3 chip",
                            ImageUrl = "/images/iMac 24.jpg",
                            Name = "iMac 24\"",
                            Price = 13000000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Liquid-cooled ultimate gaming desktop PC",
                            ImageUrl = "/images/Alienware Aurora R16.jpg",
                            Name = "Alienware Aurora R16",
                            Price = 22000000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Ergonomic wireless mouse for productivity",
                            ImageUrl = "/images/Logitech MX Master 3S.jpg",
                            Name = "Logitech MX Master 3S",
                            Price = 1000000m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Hot-swappable RGB mechanical keyboard",
                            ImageUrl = "/images/Mechanical Keyboard GMMK 2.jpg",
                            Name = "Mechanical Keyboard GMMK 2",
                            Price = 12000000m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Titanium design, Action button, A17 Pro chip",
                            ImageUrl = "/images/iPhone 15 Pro.jpg",
                            Name = "iPhone 15 Pro",
                            Price = 10000000m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Built-in S Pen, Galaxy AI, 200MP Camera",
                            ImageUrl = "/images/Samsung Galaxy S24 Ultra.jpg",
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 12000000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
